// Generated by CoffeeScript 1.10.0
(function() {
  var client, d, e, g, h, svg, w;

  client = new $.RestClient('http://karlduino3.local/arduino/robot/');

  client.add("forward");

  client.add("backward");

  client.add("stop");

  client.add("right");

  client.add("left");

  $("#Forward").click(function() {
    return client.forward.read();
  });

  $("#Stop").click(function() {
    return client.stop.read();
  });

  $("#Backward").click(function() {
    return client.backward.read();
  });

  $("#Left").click(function() {
    return client.left.read();
  });

  $("#Right").click(function() {
    return client.right.read();
  });

  w = window;

  d = document;

  e = d.documentElement;

  g = d.getElementsByTagName('body')[0];

  w = w.innerWidth || e.clientWidth || g.clientWidth;

  h = w.innerHeight || e.clientHeight || g.clientHeight;

  if (w > 300) {
    w = 300;
  }

  if (h > 300) {
    h = 300;
  }

  svg = d3.select("div#for_svg").append("svg").attr("height", h).attr("width", w);

  svg.append("rect").attr("height", h).attr("width", w).attr("x", 0).attr("y", 0).attr("fill", "#ccc");

}).call(this);
