// Generated by CoffeeScript 1.10.0
(function() {
  var bev, client, color, gapx, gapy, h, hilit, lab, rh, rw, svg, w, x, y;

  client = new $.RestClient('http://karlduino3.local/arduino/robot/');

  client.add("forward");

  client.add("backward");

  client.add("stop");

  client.add("right");

  client.add("left");

  color = "slateblue";

  hilit = "Orchid";

  gapx = 5;

  gapy = 5;

  rw = 150;

  rh = 50;

  bev = 10;

  w = gapx * 4 + rw * 3;

  h = gapy * 4 + rh * 3;

  svg = d3.select("div#for_svg").append("svg").attr("height", h).attr("width", w);

  y = [gapy, gapy * 2 + rh, gapy * 2 + rh, gapy * 2 + rh, gapy * 3 + rh * 2];

  x = [gapx + rw, 0, gapx + rw, gapx * 2 + rw * 2, gapx + rw];

  lab = ["forward", "left", "stop", "right", "backward"];

  svg.selectAll("empty").data(lab).enter().append("rect").attr("id", function(d) {
    return d;
  }).attr("fill", function(d) {
    if (d !== "stop") {
      return color;
    }
    return hilit;
  }).attr("x", function(d, i) {
    return x[i];
  }).attr("y", function(d, i) {
    return y[i];
  }).attr("height", rh).attr("width", rw).attr("rx", bev).attr("ry", bev).attr("stroke", color).attr("stroke-width", "3").on("click", function(d) {
    d3.selectAll("rect").attr("fill", color);
    d3.select(this).attr("fill", hilit);
    if (d === "forward") {
      client.forward.read();
    }
    if (d === "backward") {
      client.backward.read();
    }
    if (d === "stop") {
      client.stop.read();
    }
    if (d === "left") {
      client.left.read();
    }
    if (d === "right") {
      return client.right.read();
    }
  }).on("touchstart", function(d) {
    d3.selectAll("rect").attr("fill", color);
    d3.select(this).attr("fill", hilit);
    if (d === "forward") {
      client.forward.read();
    }
    if (d === "backward") {
      client.backward.read();
    }
    if (d === "stop") {
      client.stop.read();
    }
    if (d === "left") {
      client.left.read();
    }
    if (d === "right") {
      return client.right.read();
    }
  }).on("mouseover", function(d) {
    return d3.select(this).attr("stroke", hilit);
  }).on("mouseout", function(d) {
    return d3.select(this).attr("stroke", color);
  });

  svg.selectAll("empty").data(lab).enter().append("text").attr("fill", "white").style("font-size", "30px").text(function(d) {
    return d;
  }).attr("x", function(d, i) {
    return x[i] + rw / 2;
  }).attr("y", function(d, i) {
    return y[i] + rh / 2;
  }).attr("dominant-baseline", "middle").attr("text-anchor", "middle").style("pointer-events", "none");

}).call(this);
